platform:
    - x86

environment:
  global:
    CYG_ROOT: C:/cygwin
  matrix:
    -
      CYG_ARCH: x86

init:
    - 'echo System architecture: %PLATFORM%'
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# NOTE: -q MUST be used for setup.exe otherwise it will prompt for user input
install:
    - '%CYG_ROOT%\setup-%CYG_ARCH%.exe -qnNdO -R "%CYG_ROOT%" -P make -P git -P gcc-core -P ocaml -P ocaml-camlp4 -P ocaml-compiler-libs -P curl -P libncurses-devel -P m4 -P unzip'
    - '%CYG_ROOT%\setup-%CYG_ARCH%.exe -qnNdO -R "%CYG_ROOT%" -P libmpfr-devel -P patch -P flexdll'
    - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'

build_script:
    - 'setup_opam.cmd'
    - 'git clone https://github.com/infidel/opam-repository repo'
    - '%CYG_ROOT%/bin/bash -lc "opam init -y -a $OLDPWD/repo"'
    - '%CYG_ROOT%/bin/bash -lc "opam install -y ocamlfind"'
    - '%CYG_ROOT%/bin/bash -lc "opam install -y -v oasis"'

cache:
    - opam

